// "use client"
import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import ContextsToaster from "./contexts/ContextsToaster";

// import QueryClientProviderWrapper from "./contexts/QueryClientContext";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import QueryClientProviderWrapper from "./contexts/QueryClientContext";
import AuthContext from "./contexts/AuthContext";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const client=new QueryClient()
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body>
        <AuthContext>
          <ContextsToaster />
          <QueryClientProviderWrapper>
            {children}
          </QueryClientProviderWrapper>
        </AuthContext>
      </body>
    </html>
  );
}
